public class ContaLoginTeste {

    public static void main(String[] args) {
        //todo autogenerated method stub

        ContaLogin conta0 = new ContaLogin();

        conta0.setNome("luana");
        conta0.setSenha("44.4");

        System.out.println(conta0.getNome());
        System.out.println(conta0.getSenha());
    }
}
